#!/bin/sh
# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: 2026 Daniel Gardiner d/b/a FractalSQLabs
#
# demo-entrypoint.sh — first-boot setup for the FractalSQL for SQLite
# demo container (docker/Dockerfile's `demo` stage, driven by
# docker-compose.yml).
#
# A SQLite extension is per-connection state: there is no server to
# configure, no config file a loaded extension can read, and no GUCs to
# set. The standard way to apply that state on every session is a
# bootstrap snippet passed to sqlite3 via -init — the same
# load_fractalsql.sql the easy_install.sh wizard writes for host
# installs. This script writes that snippet from FRACTALSQL_* env vars
# (set in docker-compose.yml, so editing the compose environment block
# and recreating the container reconfigures reasoning), with defaults
# pointing at the compose network's `ollama` service. The snippet's
# keys, order, and shape mirror easy_install.sh's generated
# load_fractalsql.sql verbatim, so the container demo and the host
# install read identically.

set -eu

DB_DIR="${FSQL_DEMO_DB_DIR:-/work}"
DB_PATH="${FSQL_DEMO_DB:-${DB_DIR}/fractalsql_demo.sqlite}"
EXT_DIR="${FSQL_EXT_DIR:-/usr/local/lib/sqlite3}"
INIT="${FSQL_DEMO_INIT:-${DB_DIR}/demo_init.sql}"
PLUGIN="${FRACTALSQL_REASONING_PLUGIN:-${EXT_DIR}/fractalsql-reasoning-http.so}"

mkdir -p "${DB_DIR}"

cat > "${INIT}" <<EOF
-- demo_init.sql — generated by docker/demo-entrypoint.sh (demo image)
--
-- Per-session bootstrap for the FractalSQL demo container. Every
-- container session opens the database with this snippet via -init.
--
-- Configuration is per-connection (SQLite has no GUCs to persist), so
-- this runs at the top of every session. Search-only usage needs just
-- the .load line below.

.load ${EXT_DIR}/fractalsql
-- Silence the fractalsql_set() 'ok' echo rows; this snippet is -init
-- boilerplate, not part of a demo's output.
.output /dev/null
SELECT fractalsql_set('reasoning_plugin', '${PLUGIN}');
SELECT fractalsql_set('http_url', '${FRACTALSQL_HTTP_URL:-http://ollama:11434/v1/chat/completions}');
SELECT fractalsql_set('http_allow_plaintext', '${FRACTALSQL_HTTP_ALLOW_PLAINTEXT:-on}');
SELECT fractalsql_set('http_model', '${FRACTALSQL_HTTP_MODEL:-gpt-oss:20b}');
SELECT fractalsql_set('http_embed_url', '${FRACTALSQL_HTTP_EMBED_URL:-http://ollama:11434/v1/embeddings}');
SELECT fractalsql_set('http_embed_model', '${FRACTALSQL_HTTP_EMBED_MODEL:-nomic-embed-text}');
SELECT fractalsql_set('http_think', 'off');
SELECT fractalsql_set('http_think_provider', 'ollama');
.output stdout
EOF

# The demo database lives on the compose demo_data volume, which starts
# empty: create it in WAL mode on first boot (the mode demo/README.md
# assumes for every demo script).
if [ ! -f "${DB_PATH}" ]; then
    sqlite3 "${DB_PATH}" "PRAGMA journal_mode=WAL;"
fi

cat <<'BANNER'

  FractalSQL for SQLite - turnkey demo container

  Extension:   /usr/local/lib/sqlite3/fractalsql.so (+ reasoning plugin)
  Database:    /work/fractalsql_demo.sqlite (WAL mode)
  Demos:       /demo/  (re-runnable .sql scripts, none run at init)

  Quick test (no model needed; base Sniper search needs no LLM):
    docker compose exec demo sqlite3 fractalsql_demo.sqlite \
      -init demo_init.sql ".read /demo/demo.sql"
    (demo.sql sections 0-2 run without a model; sections 3-4 get a
    clear model-not-found error from Ollama until step 2 pulls one)

  Confirm the edition/version:
    docker compose exec demo sqlite3 fractalsql_demo.sqlite \
      -init demo_init.sql "SELECT fractalsql_edition(), fractalsql_version();"

  Pull the reasoning model (opt-in, ~13.8GB; nothing pulls it for you):
    docker compose --profile pull-model run --rm pull-model

  Run any demo:
    docker compose exec demo sqlite3 fractalsql_demo.sqlite \
      -init demo_init.sql ".read /demo/demo-vertical-medtech-clinical.sql"
  Interactive sqlite3 shell (reasoning pre-configured):
    docker compose exec demo sqlite3 fractalsql_demo.sqlite -init demo_init.sql
  Full demo list:
    docker compose exec demo ls /demo/

  Docs: docs/docker-demo.md (in the repo / mounted volume)

BANNER

exec "$@"